# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20160505_0043'),
        ('myapp', '0015_auto_20160504_1731'),
    ]

    operations = [
    ]
