# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-29 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='da',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='pa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
